on: [push]

jobs:
  test:
    strategy:
      matrix:
        rosdistro: [jazzy, rolling]
    name: "ROS ${{ matrix.rosdistro }}"
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-noble-latest
    steps:
      - name: Build and run tests
        uses: ros-tooling/action-ros-ci@v0.4
        with:
          package-name: rosfmt
          target-ros2-distro: ${{ matrix.rosdistro }}
